apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "spring-jar-app"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["spring-jar-app-service.spring-jar:8080"]

      - job_name: "spring-native-app"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["spring-native-app-service.spring-native:8080"]

      - job_name: "spring-jar-app-arm"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["spring-jar-app-arm-service.spring-jar-arm:8080"]

      - job_name: "spring-native-app-arm"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["spring-native-app-arm-service.spring-native-arm:8080"]

      - job_name: "kubernetes-pods"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
