apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-native-app-arm
  namespace: spring-native-arm
  labels:
    app: spring-native-app-arm
    version: native
    tier: backend
    architecture: arm64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-native-app-arm
      version: native
  template:
    metadata:
      labels:
        app: spring-native-app-arm
        version: native
        tier: backend
        architecture: arm64
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: spring-native-app-arm
        image: ghcr.io/adrianbp/spring-native-servlet-poc-native-arm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:testdb"
        - name: ARCHITECTURE
          value: "arm64"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/users/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/users/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/users/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
