apiVersion: v1
kind: Service
metadata:
  name: spring-native-app-arm-loadbalancer
  namespace: spring-native-arm
  labels:
    app: spring-native-app-arm
    version: native
    architecture: arm64
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-native-app-arm
    version: native
