global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-jar'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-jar:8080']
    scrape_interval: 10s

  - job_name: 'spring-native'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-native:8080']
    scrape_interval: 10s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
