apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-native-app
  namespace: spring-native
  labels:
    app: spring-native-app
    version: native
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-native-app
      version: native
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: spring-native-app
        version: native
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
        dynakube.dynatrace.com/inject: "true"
        opentelemetry.io/service-name: "spring-native-app"
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: spring-native-app
        image: ghcr.io/adrianbp/spring-native-servlet-poc-native:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:testdb"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/users/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/users/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/users/health
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
