name: CI/CD Native Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-native
  ENVIRONMENT_URL: ${{ secrets.DYNATRACE_ENVIRONMENT_URL }}
  API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn clean test

  build-native:
    name: Build Native Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up GraalVM JDK 17
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
      
    - name: Build native image
      run: mvn clean -Pnative native:compile
      
    - name: Upload native binary and Dynatrace agent
      uses: actions/upload-artifact@v4
      with:
        name: native-binary-and-dynatrace
        path: |
          target/native-jpa-servlet
          target/dynatrace
        retention-days: 5

  build-docker-native:
    name: Build and Push Native Docker Image
    runs-on: ubuntu-latest
    needs: build-native
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Download native binary and Dynatrace agent
      uses: actions/download-artifact@v4
      with:
        name: native-binary-and-dynatrace
        path: target/
        
    - name: Make binary executable
      run: chmod +x target/native-jpa-servlet
      
    - name: List target directory contents (Debug)
      run: |
        echo "Listing target directory:"
        ls -la target/
        echo "Listing Dynatrace directory:"
        ls -la target/dynatrace/ || echo "Dynatrace directory not found"
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.native
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy-native:
    name: Deploy Native to Kubernetes
    runs-on: ubuntu-latest
    needs: build-docker-native
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-west-2 --name spring-native-poc-cluster
      
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/native/
        kubectl rollout restart deployment/spring-native-app -n spring-native
        kubectl rollout status deployment/spring-native-app -n spring-native --timeout=600s
